// 本机"其它桥进程"的扫描与清理（宿主与桥共用一份实现）。
//
// 用途：
//   · 宿主：每次 startBridge 前先接管残留桥（上次 DSH 被强杀留下的孤儿、另一个 DSH 实例起的桥）；
//   · 桥：自己被 relay 反复按 "duplicate connection" 顶替时自愈（本机还有另一个桥，且多半是老版本、
//         不认识单例锁）——主动清掉对方，避免手机端一直"刷新不出会话"。
//
// 分类（命令行必须形如 `<node 解释器> …\bridge\main.js …`，"桥入口是脚本参数"才算桥，
// 因此不会误伤恰好提到该路径的其它进程；本机实测：只命中真桥）：
//   · own      ：带 `--state-dir=<本插件 stateDir>` —— 与本宿主/本桥同一个 relay 身份，必须清掉；
//   · legacy   ：没有任何 `--state-dir=` 参数 —— 旧版本桥（不认单例锁），默认也清掉（否则会一直互踢）；
//   · otherNew ：带别的 `--state-dir=` —— 另一份身份（临时第二桥/测试），**不动**。
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SCAN_RX = "node(\\.exe)?\"?\\s+\"?[^\"]*bridge[\\\\/]main\\.js";

/** 本机所有桥进程：[{ pid, hasMarker, own }]，不含当前进程。 */
export function scanBridgeProcs(stateDir) {
  const empty = { procs: [], error: null };
  if (process.platform !== "win32") return empty; // 当前用户全是 Windows；其它平台靠单例锁即可
  const scanFile = stateDir ? join(stateDir, "takeover-scan.ps1") : null;
  // .ps1 必须是 ASCII：Windows PowerShell 5.1 对无 BOM 文件按 ANSI 解析，中文注释会被弄坏
  const script = [
    "# generated by @zdx8637/dshmobile-bridge: list bridge processes (node + bridge/main.js as script arg)",
    `$rx = '${SCAN_RX}'`,
    "$marker = '--state-dir='",
    "Get-CimInstance Win32_Process -Filter \"name='node.exe'\" |",
    "  Where-Object { $_.CommandLine -match $rx } |",
    "  ForEach-Object { \"$($_.ProcessId) $($_.CommandLine.Contains($marker)) $($_.CommandLine.Contains($marker + '" + (stateDir ?? "") + "'))\" }",
  ].join("\n");
  if (scanFile) {
    try {
      mkdirSync(stateDir, { recursive: true });
      writeFileSync(scanFile, script, "utf8");
    } catch { /* 写不了就沿用上次的脚本文件 */ }
  }
  const cmds = scanFile
    ? ["pwsh", "powershell"].map((exe) => `${exe} -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "${scanFile}"`)
    : ["pwsh", "powershell"].map((exe) => `${exe} -NoProfile -NonInteractive -Command "${script.replace(/"/g, '\\"')}"`);
  let lastErr = null;
  for (const cmd of cmds) {
    try {
      const out = execSync(cmd, { encoding: "utf8", timeout: 15000, windowsHide: true, stdio: ["ignore", "pipe", "ignore"] });
      const procs = out
        .split(/\r?\n/)
        .map((line) => line.trim().split(/\s+/))
        .filter((parts) => parts.length >= 3)
        .map(([pid, hasMarker, own]) => ({ pid: Number(pid), hasMarker: hasMarker === "True", own: own === "True" }))
        .filter((p) => Number.isInteger(p.pid) && p.pid > 0 && p.pid !== process.pid);
      return { procs, error: null };
    } catch (err) {
      lastErr = err;
    }
  }
  return { procs: [], error: lastErr };
}

/**
 * 清理本机其它桥进程（保留自己）。
 * @param {{stateDir?:string, includeLegacy?:boolean, log?:(m:string)=>void}} opts
 *        includeLegacy=true 时连"旧版本桥（无 state-dir 标记）"一起清——宿主接管与桥自愈都用它；
 *        测试里传 false，只清与本身份相同（同 stateDir 标记）的桥，避免误伤开发机上的生产桥。
 * @returns {{killed:number[], failed:number[], skipped:number[], error:any}}
 */
export function killOtherBridges({ stateDir, includeLegacy = true, log = console.log } = {}) {
  const { procs, error } = scanBridgeProcs(stateDir);
  const killed = [];
  const failed = [];
  const skipped = [];
  for (const p of procs) {
    const target = p.own || (includeLegacy && !p.hasMarker);
    if (!target) {
      skipped.push(p.pid);
      continue;
    }
    try {
      process.kill(p.pid);
      killed.push(p.pid);
      log(`[scan] 已结束其它桥进程 pid=${p.pid}（${p.own ? "同一身份" : "旧版本桥"}，避免双桥互踢）`);
    } catch {
      failed.push(p.pid);
    }
  }
  return { killed, failed, skipped, error };
}
